# Definition of a specific environment

name: environment   # environment unique name
repository: repository  # algorithm source code
commit: version   # environment specific version
diff: ""   # an optional path to a git patch file (or empty string if worktree is clean)
params: {}  # a dict of parameters.
