# Definition of a specific environment

name: environment   # environment unique name
repository: repository  # algorithm source code
commit: version   # environment specific version
diff: ""   # if present, the git diff since commit used for this run.
params:  # a dict of environment parameters.
